name: unfrezze server

on:
  workflow_dispatch:
  schedule:
    - cron: '*/12 * * * *'

jobs:
  petition:
    runs-on: ubuntu-latest

    steps:

      - name: HTTP request
        run: |
          curl -X GET "https://backend-image-upload-59qx.onrender.com"
